export const UPDATE_COLLECTION_FIELD = 'UPDATE_COLLECTION_FIELD';

export const CREATE_COLLECTION = 'CREATE_COLLECTION';
export const TOGGLE_FIELD = 'TOGGLE_FIELD';

export const COLLECTION_CREATED = 'COLLECTION_CREATED';

export const ADD_CARD_TO_COLLECTION = 'ADD_CARD_TO_COLLECTION';
export const CARD_ARRAY_SAVED = 'CARD_ARRAY_SAVED';

export const REMOVE_CARD_FROM_TEMPORARY_ARRAY =
  'REMOVE_CARD_FROM_TEMPORARY_ARRAY';

export const EDIT_CARD_IN_ARRAY = 'EDIT_CARD_IN_ARRAY';
