export const UPDATE_COLLECTION_FIELD = 'UPDATE_COLLECTION_FIELD';

export const CREATE_COLLECTION = 'CREATE_COLLECTION';
export const UPDATE_CHECKBOX = 'UPDATE_CHECKBOX';

export const COLLECTION_CREATED = 'COLLECTION_CREATED';

export const ADD_CARD_TO_COLLECTION = 'ADD_CARD_TO_COLLECTION';
export const CARD_ARRAY_SAVED = 'CARD_ARRAY_SAVED';
