export const UPDATE_COLLECTION_FIELD = 'UPDATE_COLLECTION_FIELD';

export const CREATE_COLLECTION = 'CREATE_COLLECTION';
export const UPDATE_CHECKBOX = 'UPDATE_CHECKBOX';

export const COLLECTION_CREATED = 'COLLECTION_CREATED';

export const ADD_CARD = "ADD_CARD"